spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springboot-db.cwg5utjhpcbg.ap-northeast-2.rds.amazonaws.com:3306/kakaobank
    username: osy9536
    password: ~tpdud434861

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      credentials:
        secret-key: xvwqLYlQ4Fsia/4uZivpb04cdTpSvHkkITNeJXsD
        access-key: AKIARUQV62IZEE6IFOTV